import test from 'node:test';import assert from 'node:assert/strict';import {D1Rest} from './d1-rest.mjs';
const account='1d08b2fb0d19775b304a616ab3d4a48f',database='d3f67da7-60a3-44b6-9215-28665492d3f9';
const result=(rows=[])=>({success:true,results:rows,meta:{rows_read:1,rows_written:0}});
function dbWith(fetchImpl){return new D1Rest({account,database,token:'unit-fixture',fetchImpl});}
test('bind is immutable and first returns scalar with metadata',async()=>{const db=dbWith(async(u,i)=>{assert.equal(u,`https://api.cloudflare.com/client/v4/accounts/${account}/d1/database/${database}/query`);assert.deepEqual(JSON.parse(i.body),{sql:'SELECT ?',params:['x']});return Response.json({success:true,result:[result([{a:'x'}])]});});const q=db.prepare('SELECT ?');assert.equal(await q.bind('x').first('a'),'x');assert.deepEqual(q.params,[]);assert.equal(db.metrics.rows_read,1);assert.equal(db.metrics.statements[0].sql,'SELECT ?');assert.equal(db.metrics.statements[0].rows_read,1);assert.ok(!('params' in db.metrics.statements[0]));});
test('batch shape and result order',async()=>{const db=dbWith(async(u,i)=>{assert.equal(JSON.parse(i.body).batch.length,2);return Response.json({success:true,result:[result([{a:1}]),result([{a:2}])]});});assert.deepEqual((await db.batch([db.prepare('a'),db.prepare('b')])).map(r=>r.results[0].a),[1,2]);assert.equal(db.metrics.queries,2);});
test('null first',async()=>{const db=dbWith(async()=>Response.json({success:true,result:[result()]}));assert.equal(await db.prepare('q').first(),null);});
test('unsupported bind rejected',()=>{const db=dbWith(()=>{});assert.throws(()=>db.prepare('q').bind(undefined));});
test('cross database batch rejected',async()=>{const a=dbWith(()=>{}),b=dbWith(()=>{});await assert.rejects(a.batch([b.prepare('q')]),/Cross-database/);});
for(const body of [{success:false,errors:[{code:1}]},{success:true,result:[]},{success:true,result:[{success:false,results:[]}]},{success:true,result:[{success:true,results:[],meta:{}}]}])test('failure is not success '+JSON.stringify(body),async()=>{let calls=0;const db=dbWith(async()=>{calls++;return Response.json(body)});await assert.rejects(db.prepare('q').all());assert.equal(calls,1);});
test('HTTP failures never retried as writes',async()=>{let calls=0;const db=dbWith(async()=>{calls++;return new Response('bad gateway',{status:502})});await assert.rejects(db.prepare('INSERT').run());assert.equal(calls,1);});
